export function formatNumber(num: number) {
  return num.toLocaleString('en-US');
}

export const mainText = (generations: number) => {
  if (generations > 0) {
    return `📸 Отправь <b>2 фото одним сообщением</b> — я создам изображение, где эти люди целуются 💋\n\n<blockquote>🪄 <b>Баланс генераций: ${generations}</b></blockquote>`;
  }
  return '📸 Отправь <b>2 фото одним сообщением</b> — я создам изображение, где эти люди целуются 💋';
};

export const friendsText = `<b>🖼 Бесплатные генерации</b>\n\n<blockquote>💡 Получайте <b>+2 генерации</b> за каждого приглашенного друга, который создаст фото.</blockquote>`;

export const subText = `<b>Для генерации подпишитесь на спонсоров</b>`;

export function groupStartText() {
  return `✋ Привет, я работаю только в личных сообщениях!`;
}

export const zeroGensText = `💰 На вашем балансе <b>0 генераций</b>, пополните баланс, чтобы продолжить\n\n<blockquote>💡 Получайте <b>+2 генерации за каждого приглашенного друга</b>, который создаст фото</blockquote>`;

// admin
export const languageToFlag: { [key: string]: string } = {
  aa: '🇪🇹',
  ab: '🇬🇪',
  af: '🇿🇦',
  ak: '🇬🇭',
  am: '🇪🇹',
  ar: '🇸🇦',
  as: '🇮🇳',
  av: '🇷🇺',
  ay: '🇧🇴',
  az: '🇦🇿',
  ba: '🇷🇺',
  be: '🇧🇾',
  bg: '🇧🇬',
  bh: '🇮🇳',
  bi: '🇻🇺',
  bm: '🇲🇱',
  bn: '🇧🇩',
  bo: '🇨🇳',
  br: '🇫🇷',
  bs: '🇧🇦',
  ca: '🇪🇸',
  ce: '🇷🇺',
  ch: '🇬🇺',
  co: '🇫🇷',
  cr: '🇨🇦',
  cs: '🇨🇿',
  cu: '🇧🇬',
  cv: '🇷🇺',
  cy: '🇬🇧',
  da: '🇩🇰',
  de: '🇩🇪',
  dv: '🇲🇻',
  dz: '🇧🇹',
  ee: '🇬🇭',
  el: '🇬🇷',
  en: '🇺🇸',
  eo: '🏳️',
  es: '🇪🇸',
  et: '🇪🇪',
  eu: '🇪🇸',
  fa: '🇮🇷',
  ff: '🇸🇳',
  fi: '🇫🇮',
  fj: '🇫🇯',
  fo: '🇫🇴',
  fr: '🇫🇷',
  fy: '🇳🇱',
  ga: '🇮🇪',
  gd: '🇬🇧',
  gl: '🇪🇸',
  gn: '🇵🇾',
  gu: '🇮🇳',
  gv: '🇮🇲',
  ha: '🇳🇬',
  he: '🇮🇱',
  hi: '🇮🇳',
  ho: '🇵🇬',
  hr: '🇭🇷',
  ht: '🇭🇹',
  hu: '🇭🇺',
  hy: '🇦🇲',
  hz: '🇳🇦',
  ia: '🏳️',
  id: '🇮🇩',
  ie: '🏳️',
  ig: '🇳🇬',
  ii: '🇨🇳',
  ik: '🇺🇸',
  io: '🏳️',
  is: '🇮🇸',
  it: '🇮🇹',
  iu: '🇨🇦',
  ja: '🇯🇵',
  jv: '🇮🇩',
  ka: '🇬🇪',
  kg: '🇨🇩',
  ki: '🇰🇪',
  kj: '🇳🇦',
  kk: '🇰🇿',
  kl: '🇬🇱',
  km: '🇰🇭',
  kn: '🇮🇳',
  ko: '🇰🇷',
  kr: '🇳🇬',
  ks: '🇮🇳',
  ku: '🇹🇷',
  kv: '🇷🇺',
  kw: '🇬🇧',
  ky: '🇰🇬',
  la: '🇻🇦',
  lb: '🇱🇺',
  lg: '🇺🇬',
  li: '🇳🇱',
  ln: '🇨🇩',
  lo: '🇱🇦',
  lt: '🇱🇹',
  lu: '🇨🇩',
  lv: '🇱🇻',
  mg: '🇲🇬',
  mh: '🇲🇭',
  mi: '🇳🇿',
  mk: '🇲🇰',
  ml: '🇮🇳',
  mn: '🇲🇳',
  mr: '🇮🇳',
  ms: '🇲🇾',
  mt: '🇲🇹',
  my: '🇲🇲',
  na: '🇳🇷',
  nb: '🇳🇴',
  nd: '🇿🇼',
  ne: '🇳🇵',
  ng: '🇳🇦',
  nl: '🇳🇱',
  nn: '🇳🇴',
  no: '🇳🇴',
  nr: '🇿🇦',
  nv: '🇺🇸',
  ny: '🇲🇼',
  oc: '🇫🇷',
  oj: '🇨🇦',
  om: '🇪🇹',
  or: '🇮🇳',
  os: '🇬🇪',
  pa: '🇮🇳',
  pi: '🇮🇳',
  pl: '🇵🇱',
  ps: '🇦🇫',
  pt: '🇧🇷',
  qu: '🇵🇪',
  rm: '🇨🇭',
  rn: '🇧🇮',
  ro: '🇷🇴',
  ru: '🇷🇺',
  rw: '🇷🇼',
  sa: '🇮🇳',
  sc: '🇮🇹',
  sd: '🇵🇰',
  se: '🇳🇴',
  sg: '🇨🇫',
  si: '🇱🇰',
  sk: '🇸🇰',
  sl: '🇸🇮',
  sm: '🇼🇸',
  sn: '🇿🇼',
  so: '🇸🇴',
  sq: '🇦🇱',
  sr: '🇷🇸',
  ss: '🇸🇸',
  st: '🇱🇸',
  su: '🇮🇩',
  sv: '🇸🇪',
  sw: '🇰🇪',
  ta: '🇱🇰',
  te: '🇮🇳',
  tg: '🇹🇯',
  th: '🇹🇭',
  ti: '🇪🇷',
  tk: '🇹🇲',
  tl: '🇵🇭',
  tn: '🇧🇼',
  to: '🇹🇴',
  tr: '🇹🇷',
  ts: '🇿🇦',
  tt: '🇷🇺',
  tw: '🇬🇭',
  ty: '🇵🇫',
  ug: '🇨🇳',
  uk: '🇺🇦',
  ur: '🇵🇰',
  uz: '🇺🇿',
  ve: '🇿🇦',
  vi: '🇻🇳',
  vo: '🏳️',
  wa: '🇧🇪',
  wo: '🇸🇳',
  xh: '🇿🇦',
  yi: '🇮🇱',
  yo: '🇳🇬',
  za: '🇨🇳',
  zh: '🇨🇳',
  zu: '🇿🇦',
  unknown: '🏳️',
};

export const statInfoText = (
  users: number,
  aliveUsers: number,
  deadUsers: number,
  groups: number,
  aliveGroups: number,
  totalMemberCount: number,
  todayStats: { users: number; groups: number },
  selfGrowth: { users: number; groups: number }
) => {
  return `<b>Общая статистика</b>

👤 <b>Юзеры: ${formatNumber(users)}</b>
🟢 Живых: ${formatNumber(aliveUsers)}
🔴 Мёртвых: ${formatNumber(deadUsers)}

💬 <b>Группы: ${formatNumber(groups)}</b>
🟢 Живых: ${formatNumber(aliveGroups)}
🔴 Мертвых: ${formatNumber(groups - aliveGroups)}
🔸 Участников: ${formatNumber(totalMemberCount)}

<b>За сегодня</b>
🟢 +${formatNumber(todayStats.users)} | 💬 +${formatNumber(todayStats.groups)}

<b>Саморост</b>
🟢 +${formatNumber(selfGrowth.users)} | 💬 +${formatNumber(selfGrowth.groups)}`;
};
